# Welcome! 

Sekarang kita berada di Notebook Meeting 19 untuk Module, Package, Library Part 1.

# **Overview**

### Create your own module



In [ ]:
!cp /content/drive/MyDrive/New module/sqroot.py

cp: cannot stat '/content/drive/MyDrive/New': No such file or directory


In [ ]:
!cp /content/drive/MyDrive/New\ module/sqroot.py /content

In [ ]:
# Import module 

import sqroot

In [ ]:
# test the module
a = [144, 10000, 9]

for i in a:
  j = sqroot.sqroot(i)
  print (j)

12.0
100.0
3.0


### Get a list of the installed Python modules using help()


In [28]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> modules

Please wait a moment while I gather a list of all available modules...



/usr/local/lib/python3.7/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/usr/local/lib/python3.7/dist-packages/datascience/tables.py:17: MatplotlibDeprecationWarning:

The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.

/usr/local/lib/python3.7/dist-packages/datascience/util.py:10: MatplotlibDeprecationWarning:

The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.



/usr/lib/python3.7/pkgutil.py:92: UserWarning:

The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them

/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:20: UserWarning:

The twython library has not been installed. Some functionality from the twitter package will not be available.

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning:

The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.



No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Cython              colorsys            keyword             reprlib
IPython             community           kiwisolver          requests
OpenGL              compileall          korean_lunar_calendar requests_oauthlib
PIL                 concurrent          lib2to3             resampy
ScreenResolution    configparser        libfuturize         resource
__future__          contextlib          libpasteurize       rlcompleter
_abc                contextlib2         librosa             rmagic
_argon2_cffi_bindings contextvars         lightgbm            rpy2
_ast                convertdate         linecache           rsa
_asyncio            copy                llvmlite            runpy
_bisect             copyreg             lmdb                samples
_blake2             coverage            locale              sched
_bootlocale         coveralls           logging             scipy
_bz2                crcmod              lsb_releas

### Get a list of the installed Python Package by using pip freeze



In [30]:
pip freeze

absl-py==1.0.0
alabaster==0.7.12
albumentations==0.1.12
altair==4.2.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arviz==0.11.4
astor==0.8.1
astropy==4.3.1
astunparse==1.6.3
atari-py==0.2.9
atomicwrites==1.4.0
attrs==21.4.0
audioread==2.1.9
autograd==1.3
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.6.3
bleach==4.1.0
blis==0.4.1
bokeh==2.3.3
Bottleneck==1.3.4
branca==0.4.2
bs4==0.0.1
CacheControl==0.12.10
cached-property==1.5.2
cachetools==4.2.4
catalogue==1.0.0
certifi==2021.10.8
cffi==1.15.0
cftime==1.6.0
chardet==3.0.4
charset-normalizer==2.0.12
click==7.1.2
cloudpickle==1.3.0
cmake==3.12.0
cmdstanpy==0.9.5
colorcet==3.0.0
colorlover==0.3.0
community==1.0.0b1
contextlib2==0.5.5
convertdate==2.4.0
coverage==3.7.1
coveralls==0.5
crcmod==1.7
cufflinks==0.17.3
cvxopt==1.2.7
cvxpy==1.0.31
cycler==0.11.0
cymem==2.0.6
Cython==0.29.28
daft==0.0.4
dask==2.12.0
datascience==0.10.6
debugpy==1.0.0
decorator==4.4.2
defusedxml==0.7.1
descartes==1.1.0
dill==0.3.4
distributed==

# **How to interact with packages**

## Using import statement



> import pandas

In [32]:
import pandas

> get a list of pandas package

In [33]:
# gunakan built-in python function yaitu dir()
dir (pandas)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 

In [38]:
# Membuat nama alias dari package, berikut nama alias yang umum digunakan

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Using from .. import.. statement



In [39]:
from sklearn.linear_model import LinearRegression

In [ ]:
dir(LinearRegression)

## Installing external Package



In [1]:
!pip install black

# **Exploring Package: NumPy**

> Basic of NumPy arrays

* Attributes of arrays

Menentukan ukuran, bentuk, memory consumption dan tipe data array

* indexing

Mendapatkan dan mengatur nilai secara individu di elemen array

* slicing

Mendapatkan dan mengatur bagian subarray dalam ukuran kecil dari array yang lebih besar


* reshaping

Merubah bentuk array 

* concatenation and splitting

Menggabungkan beberapa array menjadi 1, dan memisahkan 1 array menjadi beberapa bagian

#### NumPy array attributes

In [ ]:
# Langkah pertama yaitu melakukan import package
import numpy as np

In [30]:
# Membuat array dari Lists
np.array ([1,2,3,4])

array([1, 2, 3, 4])

In [31]:
np. array (['susi', 3.14, 2])

array(['susi', '3.14', '2'], dtype='<U32')

In [32]:
# set data type dalam array

np. array (['susi', 3.14, 2],dtype = 'float32') # non integer gagal diconvert ke float

ValueError: ignored

In [33]:
# set data type dalam array

np. array ([100.0, 3.14, 2],dtype = 'float32') 

array([100.  ,   3.14,   2.  ], dtype=float32)

In [34]:
# Bagaimana jika kita butuh array yang besar?

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
# buat 3x5 array yang diisi dengan 1 dan tipe data adalah float
np.ones ((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# buat 3x5 array yang diisi dengan 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### Indexing

> 1-D array

In [7]:
# kita akan membuat array 1-D dengan menggunakan np.array() 
arr = np.array ([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
# akses isi array

arr [1]

2

In [9]:
# akses isi array dan buat penjumahan 

arr [1] + arr [3]

6

> 2-D array

untuk mengakses elemen yang ada di dalam array 2-D, kita akan menggunakan koma yang memisahkan dimensi dengan elemen yang ada di dalamnya.

In [27]:
array2 = np.array ([[1,2,3,4,5], # dimensi 1 
                  [6,7,8,9,10]]) # dimensi 2
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
type (array2)

numpy.ndarray

In [13]:
# Mengakses elemen kedua di dalam dimensi 1, yaitu = 2

array2 [0,1]

2

In [14]:
# kita coba combine hasil akses mengunakan perintah print
print ('Elemen kedua dari dimensi 1 :', array2[0,1])

Elemen kedua dari dimensi 1 : 2


In [15]:
# akses elemen ke-5 di dimensi kedua:

print ('Elemen kelima dari dimensi 2 :', array2[1,4])

Elemen kelima dari dimensi 2 : 10


> 3-D array

untuk mengakses elemen yang ada di dalam array 3-D, kita akan menggunakan koma yang memisahkan dimensi dengan elemen yang ada di dalamnya.

In [17]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# akses elemen ketiga dari array kedua  pada dimensi pertama

print ('Elemen ketiga dari array ke-2 di dimensi 1 :', array3[0,1,2])

Elemen ketiga dari array ke-2 di dimensi 1 : 6


#### Negative indexing

> Negative indexing digunakan untuk akses array mulai dari urutan akhir.

In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Elemen terakhir dari dimensi 2: ', arr[1, -1])

Elemen terakhir dari dimensi 2:  10


In [21]:
# akses elemen 5 di dimensi 1
print('Elemen terakhir dari dimensi 1: ', arr[0, -1])

Elemen terakhir dari dimensi 1:  5


#### Slicing

> Slicing di python adalah mengambil satu (atau lebih) elemen dari satu indeks ke indeks lain yang telah ditentukan. 

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[1:5]

[2 3 4 5]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[-3:-1]

[5 6]


In [37]:
arr[::2]

array([1, 3, 5, 7])

In [38]:
arr[1::2]

array([2, 4, 6])

In [39]:
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

#### Reshaping 

> mengubah 1-D array menjadi 2-D matriks baris atau kolom dengan reshape()

In [41]:
# row vector 
x = np.array ([1,2,3])
print (x)

x.reshape((1,3))

[1 2 3]


array([[1, 2, 3]])

In [42]:
# column vector
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [44]:
# column vector via new axis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Concatenation and Splitting

> menggabungkan dua array di NumPy

In [45]:
# variabel x dan y
x = np.array ([1,2,3])
y = np.array ([3,2,1])
print (x)
print (y)

[1 2 3]
[3 2 1]


In [47]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

> Menggabungkan 2 array dalam sekali code

In [48]:
# buat variabel z
z = np.array([10,10,10])

np.concatenate([x,y,z])


array([ 1,  2,  3,  3,  2,  1, 10, 10, 10])

> Menggabungkan 2-D array

In [49]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
# cek jumlah dimensi (axis) dalam array
print(np.concatenate([a,a]).ndim)

# cek shape (baris, kolom)
print (np.concatenate([a]).shape)

# cek jumlah elemen 
print (np.concatenate([a]).size)

2
(4, 4)
16


In [53]:
# menggabungkan sepanjang axis ke-2
np.concatenate ([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

> Splitting adalah kebalikan dari Concatenation

* np.split
* np.hsplit
* np.vsplit

In [56]:
# np.split
x = [1,2,3,4,5,6,7,8,9,10]

# assign ke variabel baru dengan memecah elemen dalam list 
x1,x2,x3 = np.split(x, [1,4])
x1, x2, x3

(array([1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]))

In [59]:
# np.vsplit
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# buat 2 variabel upper, lower
upper, lower = np.vsplit (a,[2])
print (upper)
print (lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [61]:
# np.hsplit

left, right = np.hsplit(a, [2])
print (left)
print (right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# References

* VanderPlas, J. (2016). Python Data Science Handbook: Essential Tools for Working with Data (1st ed.) [E-book]. O’Reilly Media.

